### ISSUE TITLE
Relaxed criteria

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/tools#1]
Allow a basic CoNLL-U format check without the extra character set and symbol list restrictions imposed by UD.

**Comment by martinpopel** [comment]
As discussed elsewhere, this format only check could either
* be the default if no `--lang` is provided. With the [online validation](http://universaldependencies.org/validation.html) (where the proper `--lang` is used), I think there is no risk of releasing an invalid treebank. Or
* introducing a new option `--formatonly` (or something like that)

It is worth considering which tests should be included in the format-only version. We agree lang-specific deprels and spaces in forms/lemmas should be allowed. What about
* the empty-node-without-dependent test (see #11) or
* SpaceAfter=No matching the raw text?

**Comment by dan-zeman** [comment]
The new validator can test on 5 levels (the --level option):

1. Only backbone CoNLL-U. Fields can be empty, except for the ID column.
2. Universal-level. UPOS, HEAD, DEPREL and DEPS must have expected values. Language-specific extensions are not checked and all are allowed (i.e., there can be any feature-value pair in FEATS).
3. Universal content-based tests. E.g. conj must go left-to-right.
4. Language-specific features, deprels, tokens with spaces. You can still use lang "ud" with this level to require that there are no language-specific extensions.
5. Language-specific content-based tests. E.g. list of lemmas that can be auxiliary verbs in the language.
