### ISSUE TITLE
Test that SpaceAfter=No corresponds with the text

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/tools#10]
@fginter: This is already fixed in https://github.com/UniversalDependencies/tools/commit/fc5b73f9956
(I planned a pull request, but have forgotten and did direct push to master, sorry.)

@dan-zeman was concerned we should not make tests more strict few days before data freeze.
So please, consider adding `--no-space-after` to the script which generates http://universaldependencies.org/validation.html
Alternatively, I can provide a script which fixes the `SpaceAfter=No` based on the text.

**Comment by fginter** [comment]
Not quite sure I understand the purpose. The test of the text attribute already checks nospaceafter. Or is this checking something else...?

**Comment by martinpopel** [comment]
> The test of the text attribute already checks nospaceafter. 

No. The original code did not check this properly, it failed to find the missing `SpaceAfter=No` (or missing space in `# text =`, depending on point of view) in [missing-space-after.conllu](https://github.com/UniversalDependencies/tools/blob/master/test-cases/nonvalid/missing-space-after.conllu) (which I added to `test-cases/nonvalid` before fixing the problem).

The problem was that `stext=stext.lstrip()` works (as a no-op) even if `stext` does not start with whitespace.

Another problem was that `runtests.sh` used `--no-tree-text`, so these kinds of problems were not tested.

I've also tried to adapt most of the `test-cases/nonvalid/*` examples, so they fail only on that one test they are focusing.
The motivation is that `runtests.sh` does not check what is the error message of `validate.py`, but we want to make sure all kinds of nonvalid cases are tested.

BTW: The tool I promised for fixing this kind of errors is [here](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/setspaceafterfromtext.py).

**Comment by fginter** [comment]
Right! Now I understand. Thanks! Good catch. Also thanks for the other commits to the test suite. Good job. 

`runtests.sh -v` at least prints the messages, so one can check the validator fails the sentence for the right reason. Admittedly this is not optimal, but since (now that v2 is in) there are no additions expected to the test suite, probably okay.

**Comment by martinpopel** [comment]
Yes, I think `runtests.sh` (and `validate.py`) is good enough for now. I am closing this issue. I just wanted to let you/all know that tests are now more strict, but `--no-space-after` can be used to revert to the original lax testing.
