### ISSUE TITLE
stats python tool

### ISSUE THREAD

**Issue by yosiasz** [UniversalDependencies/tools#101]
hello

I am not able to find the stats python script mentioned in your docu?

Thanks

**Comment by dan-zeman** [comment]
The script that computes the statistics is written in Perl, not in Python.

If you prefer Python for some reason, you can use [Udapi](https://udapi.github.io/) to collect any kind of statistics you can think of.

**Comment by yosiasz** [comment]
gotcha. so docu is wrong then

https://universaldependencies.org/tools.html#ud-maintained-tools

**Comment by martinpopel** [comment]
Yes, conllu-stats.py was [deleted on June 10, 2023](https://github.com/UniversalDependencies/tools/issues/36), so https://universaldependencies.org/tools.html#ud-maintained-tools should be updated.

**Comment by dan-zeman** [comment]
> gotcha. so docu is wrong then
> 
> https://universaldependencies.org/tools.html#ud-maintained-tools

Thanks for reporting. I did not know that the scripts were mentioned on this page. Updated now.
