### ISSUE TITLE
Online validator stuck?

### ISSUE THREAD

**Issue by lauma** [UniversalDependencies/tools#105]
Online validator shows results for several days old version of UD_Latvian-LVTB http://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl?UD_Latvian-LVTB despite the fact that I have commited several versions with way less errors.

My newly commited data is in dev branch and I checked that both tools repository is up to date and I did commit actual new data in treebank repo. I attached validation log I get localy from my data (`python validate.py --lang=lv --max-err=0 ../UD_Latvian-LVTB/lv_lvtb-ud-train.conllu ../UD_Latvian-LVTB/lv_lvtb-ud-dev.conllu ../UD_Latvian-LVTB/lv_lvtb-ud-test.conllu > ud-validator.lv.log 2>&1 `, windows), it is 60 errors locally vs. 429 errors online despite the fact that online report shows recent timestamp. I also recognise the errors online as something we actually had in treebank several days ago, but not currently anymore.

If the problem is somehow larger and can't be fixed fast, then I would like to have reasurment that I can trust local validation results over online (as long as I have up to date tools repo).

Thanks and good luck everybody with release!

[ud-validator.lv.log](https://github.com/user-attachments/files/17520138/ud-validator.lv.log)

**Comment by dan-zeman** [comment]
Thanks for reporting this! The online validator is running but something went wrong with the access rights for the UD_Latvian-LVTB folder on the server. I replaced it with a fresh clone, re-validated it, and the number of errors+warnings went down from 435 to 66. Let me know if it appears stuck again (hopefully not)!
