### ISSUE TITLE
empty-node-without-dependent.conllu

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/tools#11]
Currently, [runtests.sh](https://github.com/UniversalDependencies/tools/blob/master/runtests.sh) fails on [empty-node-without-dependent.conllu](https://github.com/UniversalDependencies/tools/blob/master/test-cases/nonvalid/empty-node-without-dependent.conllu).
This is not ideal as we plan to publish this tools repo within the UD 2.0 release.

I can fix this, but I would prefer to test this within svalidation (rather than within validate.py).
First, it would be easier to implement there (and `validate.py` is terrible to maintain even now without adding more tests).
Second, I consider this a linguistic decision, we may want to keep in UD treebanks, but not a strict requirement of the CoNLL-U format.

**Comment by fginter** [comment]
1. @spyysalo is aware of this and working on it
2. `validate.py` cannot assume valid input and therefore the code is quite complex
