### ISSUE TITLE
Enhanced representation validation

### ISSUE THREAD

**Issue by Kira-D** [UniversalDependencies/tools#18]
I prepared the enhanced representation for ru_syntagrus UD2.0 release, but unfortunately I had to abandon it because validation fails on fractional ids in DEPS field.
Did I miss something important or did I find a bug?

I have these errors:
[Line                   15187]: Undefined ID in DEPS: E4.2
[Line                   15187]: Undefined ID in DEPS: E4.2
[Line                   15187]: Undefined ID in DEPS: E4.2
[Line                   15187]: Failed to parse DEPS: E4.2:case

But the data looks ok to me:
http://paste2.org/6w2WmvG0

**Comment by fginter** [comment]
Hi Kira. You should drop the "E" and you'll be fine. So `4.2:advcl` instead of `E4.2:advcl` in DEPS. That E was in the specs for a while but was dropped later. -Filip

**Comment by fginter** [comment]
@dan-zeman can comment, but maybe the corrected version of SyntagRus could still make it into the v2 release...? I know you guys are training UDPipe now, but that probably doesn't use the enhanced representation anyway, so nothing would need to get restarted.

**Comment by dan-zeman** [comment]
Yes, it can. We will talk about it with @Kira-D.
