### ISSUE TITLE
TypeError: "validate.py" compatibility with Python 3.6

### ISSUE THREAD

**Issue by loganpeng1992** [UniversalDependencies/tools#22]
While using "validate.py" in UDtools to validate conllu-formatted GUM corpus, the following error message occurs to my computer:

"""
C:\Users\logan\Dropbox\GUM\UDtools>python validate.py --lang en ..\amir_gumdev\_build\target\dep\ud\GUM_interview_ants.conllu
Traceback (most recent call last):
  File "validate.py", line 735, in <module>
    validate(inp,out,args,tagsets,known_sent_ids)
  File "validate.py", line 613, in validate
    for comments,tree in trees(inp,tag_sets,args):
  File "validate.py", line 74, in trees
    for line_counter, line in enumerate(inp):
  File "C:\Program Files\Python36\lib\codecs.py", line 644, in __next__
    line = self.readline()
  File "C:\Program Files\Python36\lib\codecs.py", line 557, in readline
    data = self.read(readsize, firstline=True)
  File "C:\Program Files\Python36\lib\codecs.py", line 499, in read
    data = self.bytebuffer + newdata
TypeError: can't concat str to bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "validate.py", line 737, in <module>
    warn(u"Exception caught!",u"Format")
  File "validate.py", line 49, in warn
    print >> sys.stderr, (u"[%sLine                   %d]: %s"%(fn,curr_line,msg)).encode(args.err_enc)
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?
"""

I was using Python 3,6,4 with Windows 10 Home. The "conllu" file seems correctly-formatted. Interestingly, my adviser @amir-zeldes  did not encounter this problem while running the same command on his computer.

I tried my luck with Python 2.7.14 on my own and it also ran through the document successfully. Not sure why it fails with bytes/strings issue.

Thank you for your support.

Best,
Logan

**Comment by fginter** [comment]
validate.py is a Python2 program. The error you get is because Python3 interprets `print >> sys.stderr` as a bit shift operator applied to a function and a file, and (admittedly rightfully) complains. I will look into porting the code into Python3.

**Comment by Stormur** [comment]
I have also encountered this problem. Automatic conversion with 2to3 gives me this: 

b'[Line                   0]: Exception caught!'
Traceback (most recent call last):
  File "validate.py", line 787, in &lt;module&gt;
    validate(inp,out,args,tagsets,known_sent_ids)
  File "validate.py", line 650, in validate
    for comments,tree in trees(inp,tag_sets,args):
  File "validate.py", line 77, in trees
    for line_counter, line in enumerate(inp):
  File "/usr/lib/python3.5/codecs.py", line 642, in __next__
    line = self.readline()
  File "/usr/lib/python3.5/codecs.py", line 555, in readline
    data = self.read(readsize, firstline=True)
  File "/usr/lib/python3.5/codecs.py", line 497, in read
    data = self.bytebuffer + newdata
TypeError: can't concat bytes to str

When trying to run it with python 2.7, it misses the regex package. Unfortunately I have some problems installing it only for python 2.7, due to overlapping pythonic installations.

Is there an available python 3 version now?

**Comment by arademaker** [comment]
No , Python 2.7 is the one that I use

**Comment by martinpopel** [comment]
@Stormur: you should be able install the [regex](https://pypi.python.org/pypi/regex) package with `pip2 install --user regex`.
That said, it would be nice if validate.py supported both Python 2 and 3.

**Comment by arademaker** [comment]
@fginter porting to Python 3 can be other issue , right ?

**Comment by Stormur** [comment]
@martinpopel : Yes, I did it, my fault. Still, I think that a python 3 version is needed, also because it can better handle Unicode.
