### ISSUE TITLE
ref in enhanced dependencies

### ISSUE THREAD

**Issue by gossebouma** [UniversalDependencies/tools#24]
I am working on adding enhanced dependencies. 
For relative pronouns, the guidelines propose to add a 'ref' relation to the antecedent noun. However, validate.py stumbles over this, as it is not a known dependency label. Adding it to the language specific set does not help either, as it is not an extension of a known relation. Should it be added to deprel.ud?

**Comment by jnivre** [comment]
We are aware of this problem and are working on it. For the next release, the validator will apply different rules to the DEPREL and DEPS field, and there will be two sets of relations: deprel.ud and edeprel.ud. In addition to the "ref" case, "orphan" is a valid relation in DEPREL but not in DEPS.

**Comment by dan-zeman** [comment]
> "orphan" is a valid relation in DEPREL but not in DEPS.

Is it? If we maintain that all types of enhanced annotation are optional, then you could skip enhanced annotation of ellipsis (and thus keep `orphan`) but use DEPS for something else, e.g., propagation of dependencies across conjuncts.

**Comment by jnivre** [comment]
Okay. My bad. The rest of my reply was hopefully correct. :)

**Comment by dan-zeman** [comment]
I think it was :) Anyways, the way how validator finds out about `ref` should be transparent for most users.

**Comment by dan-zeman** [comment]
The current version of validate.py should not complain about `ref`.

https://github.com/UniversalDependencies/tools/commit/5906a1c2629536bc98c3a3aee54757d20df61d73
