### ISSUE TITLE
[validate.py] ImportError: No module named file_util

### ISSUE THREAD

**Issue by odanoburu** [UniversalDependencies/tools#27]
- I'm using `Python 2.7.15rc1` that comes by default in Ubuntu 18.04
- the only things I ever installed where `pip` and `virtualenv`
- the code was run in a `virtualenv` where I installed the `regex` module. 

I thought the `file_util` module was built-in, but apparently it isn't (at least in this python version). I tried `pip install distutils` to no avail. what's the name of the package I should install? (a `requirements.txt` file would be useful!)

**Comment by odanoburu** [comment]
indeed, @dan-zeman, thanks! it's funny because there is a file_util in the `distutils` package, which is why I was confused. I also thought this was a standalone script, so I didn't bother cloning the repository..

do you know how can I see all the errors (some are suppressed)?

```
...suppressing further errors regarding Syntax
*** FAILED *** with 3423 errors
Syntax errors: 3423
The language-specific file /home/bruno/sites/ud-tools/data/edeprel.en does not exist.
```

I am running `validate.py` in the English-EWT test corpus.

**Comment by dan-zeman** [comment]
I think there is a --maxerrors option or something like that.

**Comment by odanoburu** [comment]
yes

```
--max-err MAX_ERR  How many errors to output before exiting? 0 for all. Default: 20.
```

thank you!
