### ISSUE TITLE
Single-rooted trees

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/tools#3]
When preparing the Finnish release, we were bitten badly by the fact that the validator does not warn on forests. That is in the specs, so that's not a bug. Nevertheless, I added a `--single-root` argument which checks that the tree is single-rooted. Now the question is, whether this shouldn't be the default behavior, with the option to switch that check off if the analyses in some particular treebank are really meant to allow multiple roots.

**Comment by manning** [comment]
Yes, I think that single-rooted should be the default. My belief is that that is how UD is meant to work....
