### ISSUE TITLE
Report sent_id in errors

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/tools#30]
`[Tree number 4093 on line 86571]: Mismatch between the text attribute and the FORM field.`

You `cat *.conllu` to pipe to `validate.py` to check for duplicate ids and whatnot. After the script is done with the first file, line numbers become non-informative. `# sent_id`s would reliably id the erroneous sentence.

**Comment by dan-zeman** [comment]
The new validator (for Python 3) reports both the line number and the sentence id:

<pre>./validate.sh --lang uk --max-err=10 UD_Ukrainian-IU/uk_iu-ud-dev.conllu
[Line 2789 Sent 142p]: Punctuation must not cause non-projectivity of nodes [31]
[Line 3867 Sent 2syn]: 'cc' not expected to have children ({'punct'})
[Line 4818 Sent 1l2x]: 'cop' not expected to have children ({'advmod'})
[Line 5097 Sent 1l8v]: 'cop' not expected to have children ({'advmod'})
[Line 5722 Sent 1lok]: 'advmod' should be 'ADV' but it is 'DET'
[Line 6250 Sent 1m1g]: 'aux' not expected to have children ({'advmod'})
[Line 7292 Sent 1wwz]: 'cop' not expected to have children ({'advmod'})
[Line 9331 Sent 1yg5]: 'cop' not expected to have children ({'advmod'})
[Line 9332 Sent 1yg5]: 'advmod' should be 'ADV' but it is 'DET'
...suppressing further errors regarding Syntax
*** FAILED *** with 17 errors
Syntax errors: 17</pre>

**Comment by msklvsk** [comment]
Cool! 

Off the topic, I have some objections to the new validation rules.

- That non-projective punctuation is an author’s `appos`, put after the quotes, in regard to something inside the quotes. Seems legit?  
<img width="588" alt="image" src="https://user-images.githubusercontent.com/473012/48957457-59aa4f80-ef61-11e8-9049-ccd73dda028b.png">

- That comma after `cc` is really unnecessary but the author put it there.
- Those `cop` children are negations and should indeed be moved up (and internally labeled with #phrase-modification). However, what about [Gloss]: _She **not** **was** the-best, she **is** the-best!_
- [`advmod:det`](http://universaldependencies.org/uk/dep/advmod-det.html) is a lang-specific phenomenon. Not sure how to analyze it in a better way.

Are the new validation rules mature enough so a separate issue can be opened to discuss them?

**Comment by dan-zeman** [comment]
The new validation rules are mature enough for separate issues to be opened (preferably in the [docs issue tracker](https://github.com/UniversalDependencies/docs/issues)) about individual rules. Otherwise they are not mature, which means that discussion is welcome :-)
