### ISSUE TITLE
Is there a script that can convert from PTB to UD in CoNLL-U style?

### ISSUE THREAD

**Issue by freesunshine0316** [UniversalDependencies/tools#31]
Hi,

   Is there a script within this repository that can convert from PTB to UD in CoNLL-U style?
   Thanks.

**Comment by sebschu** [comment]
Yes, the UD converter as part of Stanford NLP can do that.

https://nlp.stanford.edu/software/stanford-dependencies.html

However, the official release still converts to UD v1. You can download an experimental version of corenlp which converts to UD v2 here but note that this version hasn’t been extensively tested at this point.

https://nlp.stanford.edu/~sebschu/files/javanlp-core-src.jar


________________________________

**Comment by freesunshine0316** [comment]
Thanks for the prompt reply @sebschu.
By the way, I found that the dependency annotations of SANCL (https://sites.google.com/site/sancl2012/home/shared-task) is different from UD v1, and is different from Stanford dependency either. Do you know what annotation guideline it uses? Thanks.

**Comment by jnivre** [comment]
According to the documentation, it should be a version of Stanford dependencies, produced by the Stanford converter from PTB annotation.

**Comment by freesunshine0316** [comment]
Hi, professor Nivre. 

Thank you for your reply. I just started doing some projects on dependency parsing. I thought one key feature of Stanford dependency is that it moves prepositions into the edge labels, maybe I was confused by a Figure in https://nlp.stanford.edu/software/stanford-dependencies.html.

By the way, this is Linfeng Song, who interned at IBM this summer and Miryam was my office mate.

**Comment by nschneid** [comment]
> I thought one key feature of Stanford dependency is that it moves prepositions into the edge labels, maybe I was confused by a Figure in https://nlp.stanford.edu/software/stanford-dependencies.html.

Figures 1 and 2 on that page show different varieties of Stanford Dependencies. Prepositions are included on the edge labels in Figure 1 but not Figure 2.

UD does not have `prep` or `pobj` labels; instead `case`, `nmod`, and (in UDv2) `obl` are used for prepositional phrases.

**Comment by freesunshine0316** [comment]
@nschneid Thanks!
