### ISSUE TITLE
Is there a way to convert 2.0 UD to 1.0 UD?

### ISSUE THREAD

**Issue by freesunshine0316** [UniversalDependencies/tools#33]

**Comment by martinpopel** [comment]
You can try to revert the [convert1to2.py](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/convert1to2.py) script, but you will encounter several difficulties. Also annotation guidelines for some constructions were underspecified in UD 1.0, so it is not possible to create a general 2to1 tool, but rather a tool specific for a given treebank.

**Comment by freesunshine0316** [comment]
@martinpopel thanks. I also found that there are many-to-one mappings from v1 to v2, so I guess it's impossible to make exact revert. Anyway, I've bypassed this problem.
