### ISSUE TITLE
Validation rules for the det relation

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/tools#38]
In the current validator, the UPOS constraint rule about `advmod` dependant is not applied if this dependant is in a `fixed` construction.
I Propose to add the same exception to other relations and in particular to the `det` relation.

In several French corpora, _n'importe quel_ is annotated as 3 tokens with `fixed` relations and it is used as a determiner (see [Grew-match](http://match.grew.fr/?corpus=UD_French-GSD@2.3&custom=5c7937a73dadd)).
This construction is invalid and would be valid with the proposition above.

**Comment by dan-zeman** [comment]
Fixed in 86f79161f0664619e5095c24c8a37776d0d3e8e2.
