### ISSUE TITLE
Validation is not exhaustive in checking non-projective punctuation

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/tools#41]
The current dev branch of the corpus `UD_French-GSD` is valid even if it contains a few cases of non-projective punctuation.

See [3 examples](http://match.grew.fr/?corpus=UD_French-GSD@dev&custom=5c7d9ae2911aa) (the request takes some times to execute (about 15s) because the pattern is not connected…)

**Comment by dan-zeman** [comment]
> The current dev branch of the corpus UD_French-GSD is valid

Great! Congratulations :-)

> even if it contains a few cases of non-projective punctuation.

Thanks! It looks like a wrong usage of Python `range()` on my part. Should be fixed in 07b44bb8528f96ab6077d4e72a174e9ad422e0cd. Welcome back in the invalid club :-)
