### ISSUE TITLE
Typo=Yes

### ISSUE THREAD

**Issue by lauma** [UniversalDependencies/tools#55]
Could it be that validator doesn't know about morpho feature "Typo=Yes", even though it is described in universal guidelines?  I added a new version for Latvian and got lots of warnings `[L4 Morpho unknown-feature-value] Unknown feature-value pair 'Typo=Yes'.` Or is it some typo on my side?

**Comment by nschneid** [comment]
I assume it's because it's not listed at https://github.com/UniversalDependencies/tools/blob/master/data/feat_val.la

**Comment by dan-zeman** [comment]
There is a discrepancy in the guidelines. `Typo=Yes` has now made it to the [guidelines on typos](https://universaldependencies.org/u/overview/typos.html) but not to the [documentation of universal features](https://universaldependencies.org/u/feat/index.html), although it actually has [its own documentation page](https://universaldependencies.org/u/feat/Typo.html).

Perhaps we should add it to the list and tell the validator to make it available in all languages.

**Comment by lauma** [comment]
Thank you! That is exactly what I meant.
