### ISSUE TITLE
Two new lines result in multiple root error in iwpt20_xud_eval

### ISSUE THREAD

**Issue by mdelhoneux** [UniversalDependencies/tools#60]
https://github.com/UniversalDependencies/tools/blob/925b8298b124f494d011f7f564b7732f92141e1c/iwpt20_xud_eval.py#L344

If sentences are separated by two new lines instead of one, the script fails on this line because it finds that there is not exactly one root: there is none. Running into this error for this is a bit confusing, maybe two new lines should be caught beforehand, or the error message could be updated.

**Comment by dseddah** [comment]
HI Myriam,
we'll look at it. Thanks for the report. 


Best,
Djamé

**Comment by gossebouma** [comment]
Fixed
