### ISSUE TITLE
Auxiliary or auxiliary verb?

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/tools#77]
I'm getting this error,

```
[Line 18810 Sent ...:18 Node 2]: [L5 Morpho aux-lemma] '...' is not an auxiliary verb in language [...] (there are no known approved auxiliaries in this language)
```

The item in question is not an auxiliary verb, but rather another kind of auxiliary word, should the message be changed to just "is not an auxiliary in language ..." ?

**Comment by dan-zeman** [comment]
OK, I can change the message because it may be misleading. (But it is not technically wrong if it says it is not an auxiliary verb and you confirmed it indeed isn't :-) Once the auxiliary is registered properly, the message will not appear again.)
