### ISSUE TITLE
Incorrect string comparison in `check_files.pl`

### ISSUE THREAD

**Issue by mr-martian** [UniversalDependencies/tools#83]
https://github.com/UniversalDependencies/tools/blob/a7cf45e00532bc0da45de5bc8c7f0200243c5dee/check_files.pl#L903

This line validates treebank version numbers using orthographic comparison, which will no longer work properly now that there exist treebanks like Ancient Hebrew-PTNK which have `Data available since: 2.10`, since `'2.10' < '2.9'`.

**Comment by martinpopel** [comment]
```perl
use version;
...
elsif(!defined($correct) && version->parse($claimed) < version->parse($current_release)) 
```
