### ISSUE TITLE
Validation rule for Foreign feature

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/tools#87]
Using `validate.py` for some French data, I had the following error: 

```
[L4 Morpho feature-upos-not-permitted] Feature Foreign is not permitted with UPOS X in language [br]
```
for the CoNLL line:

```
11	maen	maen	X	_	Foreign=Yes	10	appos	_	Lang=br|SpaceAfter=No
```

I think it would be sensible to allow the feature `Foreign=Yes` on the `X` tag whatever is the language.

**Comment by tlynn747** [comment]
I might also suggest taking a look at the guideline suggestions for UGC (Section 4.7) in our recent journal article:

Treebanking user-generated content: a UD based overview of guidelines, corpora and unified recommendations
https://link.springer.com/content/pdf/10.1007/s10579-022-09581-9.pdf

**Comment by dan-zeman** [comment]
The validator should now judge the `Foreign` feature according to the main language of the corpus, regardless of `Lang=xx` in MISC.
