### ISSUE TITLE
conllu_to_text.pl as a python script?

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/tools#92]
Have you ever considered converting conllu_to_text.pl to a python script?  We are using it via subprocess in python, and rewriting it to python would make it a lot easier to use

**Comment by dan-zeman** [comment]
Not really. I consider Perl my native language and I only reach for Python when I have to (typically when I need to modify a script that someone else started in Python). If I had the time and energy to translate scripts from one language to another, I would probably convert the Python scripts in this repo to Perl :-D. But I guess there could be two versions of the script if somebody decides to write the Python version...

**Comment by AngledLuffa** [comment]
Understandable.  Thanks anyway
